### ISSUE TITLE
How About Getting it to Work on Obsidian Mobile?

### ISSUE THREAD

**Issue by guihasparyk** [jesse-r-s-hines/obsidian-autopin#1]
### Summary

I've recently used the app on my PC and it's amazing. Can you make it available also for Obsidian Mobile?

### Details

I need it to work on my mobile because some links inside the properties of pages are persistent and end up opening in the same tab, even though I have my plugin "Open In New Tab" activated.

In that way I can have a work fluid of opening links and making notes for my research.

**Comment by jesse-r-s-hines** [comment]
Glad you are finding the plugin useful!

I've enabled it for mobile, and it appears the plugin functions the same on mobile as desktop without further changes. Please open another issue if you find something that's broken on the mobile version though :smile:.

**Comment by guihasparyk** [comment]
Thank you very much. Sometimes opening the 2º page for the first time opening Obsidian it acts a little weird (duplicate and window separate) but eventually it works after that small thing.
So no worries! It works like a charm.
Great plugin.
